# fly.toml file generated for billowing-wave-8174 on 2023-04-05T20:00:46+10:00

app = "billowing-wave-8174"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "syd"
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
